font_size 12.0
font_family FiraCode Nerd Font Mono

window_padding_width 5
font_features FiraCodeNFM-Reg +cv01 +cv02 +cv06 +ss01 +ss05 +ss03 +cv31 +cv29
font_features FiraCodeNFM-SemBd +cv01 +cv02 +cv06 +ss01 +ss05 +ss03 +cv31 +cv29
font_features FiraCodeNFM-Ret +cv01 +cv02 +cv06 +ss01 +ss05 +ss03 +cv31 +cv29
