# Gruvbox Dark

# General
foreground #ebdbb2
background #1d2021
selection_foreground #655b53
selection_background #ebdbb2
url_color #d65c0d

# Black
color0 #272727
color8 #928373

# Red
color1 #cc231c
color9 #fb4833

# Green
color2 #989719
color10 #b8ba25

# Yellow
color3 #d79920
color11 #fabc2e

# Blue
color4 #448488
color12 #83a597

# Magenta
color5 #b16185
color13 #d3859a

# Cyan
color6 #689d69
color14 #8ec07b

# White
color7 #a89983
color15 #ebdbb2
