background {
	monitor =
	path = ~/.config/wallpaper.jpg
}

label {
  monitor =
  color = rgb(000000)

  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  font_size = 20

  halign = center
  valign = center
  position = 0, 300
}

label {
  monitor =
  color = rgb(000000)

  text = cmd[update:1000] echo "$(date +"%R")"
  font_size = 90

  halign = center
  valign = center
  position = 0, 200
}

label {
  monitor =
  color = rgb(000000)

  text = $USER
  font_size = 20

  halign = center
  valign = center
  position = 0, -250
}

input-field {
	monitor =
	size = 250, 50

	halign = center
	valign = center
	position = 0, -300
}
