general {
	gaps_in = 5
	gaps_out = 10

	border_size = 4
}

animations {
	enabled = true
}

decoration {
	rounding = 25

    active_opacity = 0.9
    inactive_opacity = 0.8

	shadow {
		enabled = false
	}

	blur {
		enabled = false
	}
}

misc {
	disable_hyprland_logo = true
	force_default_wallpaper = false
}
